#!/bin/bash

# Add all new files and remove all deleted files
#
# $ git ar

update_git_index() {
    git ls-files -d -m -o -z --exclude-standard | xargs -0 git update-index --add --remove
}

if [[ $# -eq 0 ]]; then
    # No arguments, run the update
    update_git_index
else
    echo "Usage: git ar"
    echo "This command updates the git index by adding new files and removing deleted files."
fi
