#!/usr/bin/env ruby
# Get next semantic version
#
# $ git next [major|minor|*patch|pre]
#
if ARGV[0] && ARGV[0] =~ /^-+h(elp)?$/
  puts "Usage: git next [major|minor|*patch|pre]"
  puts "Get the next semantic version number."
  puts "If no argument is given, it will increment the patch version."
  puts "Use 'major' to increment the major version, 'minor' for minor, and 'patch' or 'inc' for patch."
  puts "Use 'pre' to increment pre-release versions."
  exit
end

type = ARGV[0]

RX = /^v?(?<major>\d+)\.(?<minor>\d+)\.(?<inc>\d+)(?<pre>\S+)?/i

current = `git ver`

raise 'Not semantic versioning' unless current =~ RX

m = current.match(RX)
major = m['major'].to_i
minor = m['minor'].to_i
inc = m['inc'].to_i
pre = m['pre']

case type
when /^maj/
  major += 1
  minor = 0
  inc = 0
when /^min/
  minor += 1
  inc = 0
when /^(pat|inc|build)/
  pre = ''
  inc += 1
else
  if type =~ /^pre/
    if pre.nil? || pre.empty?
      inc += 1
      pre = 'pre'
    else
      pre.next!
    end
  elsif pre && !pre.empty?
    pre.next!
  else
    inc += 1
  end
end

$stdout.print "#{major}.#{minor}.#{inc}#{pre}"
